# Generated by Django 4.0.1 on 2022-01-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ManyToManyField(related_name='department_obj', to='FirstApp.Department'),
        ),
    ]
